#ifndef FILE_FORMAT_H
#define FILE_FORMAT_H

#define PUNCTOR_FILE_FORMAT_VAR_ID "%ID%"
#define PUNCTOR_FILE_FORMAT_VAR_TIME1 "%TIME1%"
#define PUNCTOR_FILE_FORMAT_VAR_TIME2 "%TIME2%"
#define PUNCTOR_FILE_FORMAT_VAR_CONTENT "%CONT%"

#define PUNCTOR_FILE_FORMAT_PLAIN_SEP "\n"
#define PUNCTOR_FILE_FORMAT_PLAIN_RECORD "%TIME1%"
#define PUNCTOR_FILE_FORMAT_PLAIN_TIME "hh:mm:ss.zzz"

#endif // FILE_FORMAT_H
